version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8876:80
    depends_on:
      - app
    container_name: testTask_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: testTask_app
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgres
    environment:
        POSTGRES_DB: testTask
        POSTGRES_USER: admin
        POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    container_name: testTask_db
